# Generated by Django 5.2.8 on 2026-02-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_trip"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Trip",
        ),
    ]
